name: alex_reader
description: A Nostr-based e-reader app using Purplebase library
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Nostr Protocol (implemented directly)
  # purplebase: ^0.1.0  # Not available on pub.dev
  # ndk: ^0.1.0  # Not available on pub.dev
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Database and Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.18
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Markup Parsing
  markdown: ^7.2.3
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  
  # Networking
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  
  # Utilities
  intl: ^0.18.1
  crypto: ^3.0.3
  uuid: ^4.2.1
  
  # Amber - Android app for Nostr authentication (separate app)
  # amber_signer: ^0.1.0  # Not a Flutter package
  
  # Shared Preferences
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 